version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb-meme
    restart: always
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
      - 28020:27017
    volumes:
      - ./data:/data/db